language: go

go:
  - "1.11"
  - "1.12"
  - "1.13.x"

env:
  - GO111MODULE=on

branches:
  only:
    - master

before_install:
  - wget http://apache.claz.org/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz
  - tar -zxvf zookeeper*tar.gz

install:
  - go get -t ./...

script:
  - go build ./...
  - go vet ./...
  - go test -v -race ./...